owner-repo: &owner-repo
  owner-repo: palantir/go-compiles

version: 2.1

orbs:
  go: palantir/go@0.0.11
  godel: palantir/godel@0.0.11

workflows:
  version: 2
  verify-test:
    jobs:
      - godel/verify:
          name: verify
          executor:
            name: go/golang
            version: "1.13"
            <<: *owner-repo
            module: false
          mod-cache: false
      - godel/test:
          name: test-go-1.13
          executor:
            name: go/golang
            version: "1.13"
            <<: *owner-repo
            module: false
          mod-cache: false
      - godel/test:
          name: test-go-1.12
          executor:
            name: go/golang
            version: "1.12.9"
            <<: *owner-repo
            module: false
          mod-cache: false
      - godel/test:
          name: test-go-1.11
          executor:
            name: go/golang
            version: "1.11.13"
            <<: *owner-repo
            module: false
          mod-cache: false
