version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@12.1.0
  shellcheck: circleci/shellcheck@3.2.0
  bats: circleci/bats@1.1.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/lint:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/review:
          filters: *filters
      - bats/run:
          filters: *filters
          path: ./src/tests
      - shellcheck/check:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: go-dist
          requires: [orb-tools/lint, orb-tools/pack, orb-tools/review, shellcheck/check, bats/run]
          filters: *filters
